import { useEffect } from "react";
import wordLogo from "../assets/word_icon.svg";
import { useLiveBackground } from "../components/LiveBackground";
import SelectProviderForVerification from "../components/SelectProviderForVerification/index";

function Page() {
  const { setStatus } = useLiveBackground();
  useEffect(() => {
    setStatus('idle');
  }, [setStatus]);

  return (
    <div className="container">
      <div className="logo-container">
        <a href="https://reclaimprotocol.org" target="_blank" rel="noreferrer">
          <img
            src={wordLogo}
            alt="Reclaim Protocol"
            className="logo-icon"
            style={{ height: "40px", width: "auto" }}
          />
        </a>
      </div>

      <h1 className="main-heading">Reclaim Protocol Demo</h1>

      <p className="subheading">What do you want to verify?</p>

      <SelectProviderForVerification />
      <p className="disclaimer">
        Proofs generated by Reclaim Protocol are secure and private.{" "}
        <a
          href="https://docs.reclaimprotocol.org"
          className="link"
          target="_blank"
          rel="noreferrer"
        >
          Learn More
        </a>
      </p>
    </div>
  );
}

export default Page;
