import { useSearchParams } from 'react-router'
import wordLogo from '../../assets/word_icon.svg'
import { useEffect, useState } from 'react';
import { Reclaim } from '../../service/reclaim';
import type { Proof, ReclaimProofRequest } from '@reclaimprotocol/js-sdk';
import { showSnackbar } from '../../components/Snackbar';
import { getErrorMessage } from '../../utils/error_message';

type VerificationStatus = 'starting' | 'verifying' | 'completed' | 'error';

function Page() {
    const [status, setStatus] = useState<VerificationStatus>('starting');

    const [search] = useSearchParams();
    const encodedRequest = search.get('request');

    const [proofRequest, setProofRequest] = useState<ReclaimProofRequest | null>(null);
    const [proof, setProof] = useState<Proof[] | null>(null);

    useEffect(() => {
        if (!encodedRequest) return;
        Reclaim.restoreVerificationRequest(encodedRequest).then(setProofRequest).catch((error) => {
            console.error(error);
            showSnackbar(`Could not request verification because ${getErrorMessage(error)}`);
        });
    }, [encodedRequest]);

    const startVerificationJourney = async (proofRequest: ReclaimProofRequest): Promise<void> => {
        proofRequest.triggerReclaimFlow().catch((error) => {
            console.error('Failed to trigger reclaim flow', error);
            setStatus('error');
        });

        proofRequest.startSession({
            onSuccess: (proof) => {
                console.info({ proof });
                showSnackbar(`Verification completed successfully`);
                if (Array.isArray(proof)) {
                    setProof(proof);
                } else if (typeof proof === 'string') {
                    // For backwards compatibility
                    setProof(JSON.parse(proof));
                } else {
                    // For backwards compatibility
                    setProof([proof as Proof]);
                }
                setStatus('completed');
            },
            onError: (error) => {
                console.error(error);
                showSnackbar(`Something went wrong because ${getErrorMessage(error)}`);
            },
        }).catch((error) => {
            console.error('Failed to get session information', error);
            setStatus('error');
        });

        setStatus('verifying');
    }

    useEffect(() => {
        if (!proofRequest) return;
        startVerificationJourney(proofRequest).catch((error) => {
            console.error(error);
            showSnackbar(`Could not request verification because ${getErrorMessage(error)}`);
        });
    }, [proofRequest]);

    return (
        <div className="container">
            <div className="logo-container">
                <a href="https://reclaimprotocol.org" target="_blank" rel="noreferrer">
                    <img src={wordLogo} alt="Reclaim Protocol" className="logo-icon" style={{ height: '40px', width: 'auto' }} />
                </a>
            </div>

            <h1 className="main-heading">Reclaim Protocol Demo</h1>

            <p className="subheading">
                {
                    (() => {
                        switch (status) {
                            case 'starting':
                                return <p>Starting verification...</p>;
                            case 'verifying':
                                return <p>Verifying...</p>;
                            case 'completed':
                                return <p>Verification completed successfully</p>;
                            case 'error':
                                return <p>Something went wrong</p>;
                        }
                    })()
                }
            </p>

            <p className="disclaimer">
                Proofs generated by Reclaim Protocol are secure and private. <a href="https://docs.reclaimprotocol.org" className="link" target="_blank" rel="noreferrer">Learn More</a>
            </p>
        </div>
    )
}

export default Page
